<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260215172154 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add messenger_messages table for message queue.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE messenger_messages (' .
            'id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ' .
            'body TEXT NOT NULL, ' .
            'headers TEXT NOT NULL, ' .
            'queue_name VARCHAR(190) NOT NULL, ' .
            'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ' .
            'available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ' .
            'delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ' .
            'PRIMARY KEY (id))'
        );
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
