services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shared\:
        resource: '%kernel.project_dir%/src/Shared/*'
        exclude:
            - '%kernel.project_dir%/src/Shared/{Frameworks,Tests}'
            - '%kernel.project_dir%/src/Shared/Adapters/Symfony/Maker'

    Shared\Entities\Clock\Clock: '@Shared\Entities\Clock\SystemClock'

when@dev:
    services:
        Shared\Adapters\Symfony\Maker\MakeBoundedContextInit:
            tags: ['maker.command']
        Shared\Adapters\Symfony\Maker\MakeUseCaseCreate:
            tags: ['maker.command']

when@test:
    services:
        Shared\Entities\Clock\Clock: '@Shared\Entities\Clock\FrozenClock'
