doctrine:
    orm:
        mappings:
            Admin:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Admin/Adapters/Gateway/ORM/Entity'
                prefix: 'Admin\Adapters\Gateway\ORM\Entity'
                alias: Admin
